### ISSUE TITLE
Swipe Location

### ISSUE THREAD

**Issue by taasinsaquib** [CS130-W20/team-B3#1]
## User Story
As a **Buyer**, I would like **to see what swipes are available at a specific dining hall** so that **I can choose the meal that I want**.

## Detailed Description
Need to tag available swipes to the possible dining halls that the seller has consented to sell at.
Need to figure out location API to enable this feature.

## Acceptance Criteria
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**

**Comment by jonathanaschultz** [comment]
Addressed in b3da98f
