### ISSUE TITLE
See Lowest Ask/Highest Bid for a given time interval

### ISSUE THREAD

**Issue by taasinsaquib** [CS130-W20/team-B3#11]
## User Story
As a **buyer**, I would like **to see the prices for bids and asks at a specified time** so that **I can see the best possible price for when I'm interested**.

## Detailed Description
This endpoint takes as input: the dining hall name [string], and time interval [{start: "0:00", end:"1:00"}]

**Comment by jonathanaschultz** [comment]
Addressed in 183afcf on frontend, 0862c20 in backend
