### ISSUE TITLE
Timed Swipe

### ISSUE THREAD

**Issue by taasinsaquib** [CS130-W20/team-B3#2]
## User Story
As a **Buyer**, I would like **to see what swipes are available at this time** so that **I can buy a swipe now**.

## Detailed Description
Tag swipes with a time that the seller has consented to selling at.

## Acceptance Criteria
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**

**Comment by jonathanaschultz** [comment]
Addressed in 41da948
