### ISSUE TITLE
Sell Swipe

### ISSUE THREAD

**Issue by taasinsaquib** [CS130-W20/team-B3#3]
## User Story
As a **Seller**, I would like **to list my swipes for sale at a certain price.**

## Detailed Description
Sellers can list a quantity of swipes at a certain price, specifying time ranges and dining halls that they would be willing to sell at. 

## Acceptance Criteria
- [x] Given **seller is listing swipes**, then **give options to sell at a time, place, set a price**
- [x] Given **a swipe is listed**, then **a new entry appears in the database**

**Comment by jonathanaschultz** [comment]
Addressed in dafa97a
