### ISSUE TITLE
Buy a swipe

### ISSUE THREAD

**Issue by taasinsaquib** [CS130-W20/team-B3#4]
## User Story
As a **Buyer**, I would like **to see a list of available swipes.

## Detailed Description
Allowed to sort by time and location availability. Can see the average price of the marketplace and contact the seller to set up the meeting.

## Acceptance Criteria
- [x] Given **sort by time**, then **list swipes by time availability**
- [x] Given **sort by location**, then **list swipes by dining hall**
- [x] Given **at the homepage**, then **see list of available swipes and market average**

**Comment by jonathanaschultz** [comment]
Addressed in dafa97a
